### ISSUE TITLE
No longer possible to use alphanumeric cardtypes like T-Shirt size

### ISSUE THREAD

**Issue by GeertLommers** [microsoft/azure-boards-estimate#147]
Since the last Update, Estimated T Shirt Sizes won't be stored. In fact, you can only type-in numeric values (although they're not stored), however the proces-field definition is a picklist of T Shirt Sizes.

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by Lozzzaa** [comment]
Hi
I've just downloaded the extension, and seem to have the same problem with T-Shirt sizes
Has this problem been fixed?

**Comment by TeunissenHarry** [comment]
Hai, it is fixed in the latest update.
Succes!

Met vriendelijke groet,

Harry Teunissen
Beheer Tooling ADO

T 030 - 28 68828
M 06 -30 74 58 72
***@***.******@***.***>
www.utrecht.nl<http://www.utrecht.nl/>
Gemeente Utrecht


***@***.***<https://www.facebook.com/GemeenteUtrecht> ***@***.*** <https://twitter.com/gemeenteutrecht>  ***@***.*** <https://www.linkedin.com/company/gemeente-utrecht>  ***@***.*** <https://www.utrecht.nl/nieuwsbrieven>


[Standaard]<https://www.utrecht.nl/>


________________________________
Van: Lozzzaa ***@***.***>
Verzonden: maandag 10 oktober 2022 15:29
Aan: microsoft/azure-boards-estimate ***@***.***>
CC: Teunissen, Harry ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [microsoft/azure-boards-estimate] No longer possible to use alphanumeric cardtypes like T-Shirt size (Issue #147)


Hi
I've just downloaded the extension, and seem to have the same problem with T-Shirt sizes
Has this problem been fixed?
