### ISSUE TITLE
Only show top 1000 teams/boards in drop down for new Estimate

### ISSUE THREAD

**Issue by ronaldput** [microsoft/azure-boards-estimate#18]
The extension only shows the 1000 Teams in the drop down when a new estimate is created. Can you create a possibility to search for teams and show more then 1000 - (5000 teams).

**Comment by MOlausson** [comment]
@ronaldput this sounds like a limitation although I can see other issues with having that amount of teams. Do so see errors in the development console or network log (F12)?

**Comment by hangy** [comment]
- https://github.com/microsoft/azure-boards-estimate/blob/1004739ea32fa6b211aeb82072ca4f8422aa9302/src/services/teams.ts#L28
- [Teams - Get All Teams](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/teams/get-all-teams?view=azure-devops-server-rest-5.0)

The network log might be interesting, because apparently the limit is set to 2000 teams in the request.

**Comment by MOlausson** [comment]
Agree with @hangy, the network log would be useful.
