### ISSUE TITLE
Estimate does not appear to work for on-prem isolated servers

### ISSUE THREAD

**Issue by amsga** [microsoft/azure-boards-estimate#257]
When installed on an on-prem server, all users appear to be getting the "Connecting to server..." message.
When checking on the network flow, it appears to be trying to connect to the internet to a msdevlabs-estimate-backend.azurewebsites.net domain.
The network does not have access to the internet.

**Comment by MOlausson** [comment]
Hi @amsga, we are looking into how we can improve this but unlikely to have a quick fix for it. The cause of the error is because we use a public endpoint to send out updates when the team is voting on items. If your browser cannot connect to the endpoint the extension fails like you describe.

The option you have at the moment is to use the offline mode where the notification endpoint isn't used. Give it a try and see if it works for you.
