### ISSUE TITLE
Developer vote "?" counted as 0 in average calculation

### ISSUE THREAD

**Issue by hedberg90** [microsoft/azure-boards-estimate#28]
**Repo steps.**
Get 5 developers to vote on issue.
Developers votes 13, 13, 13, 21, and "?"

**Actual result**
Average presented 12   (60/5)

**Expected result**
Average presented 15  (60/4) 
"?" is ignored in average calculation

**Comment by MOlausson** [comment]
@hedberg90 ? is like null to me, it's hard to decide what is correct. But in general I agree that it should affect the average, question is if it should invalidate the result all together. What do you think?

**Comment by hedberg90** [comment]
@MOlausson That is a valid point. I'll explain our specific use case.  
In our use case the "?" is the developer that first and foremost is working frontend, and the vote is on a pure backend topic. He votes on every issue, like the other backend and fullstack developers, it can be hard for the leader on the estimation session to know how many votes you get on each item so everyone votes on all topics. This is maybe not as intended.

**Comment by MOlausson** [comment]
@hedberg90 I like the explanation and I think it makes sense to support this. Will discuss with the team if it should be the default or if we should make it configurable.

**Comment by byamagata** [comment]
I have something similar to this as well, 

@MOlausson what was the original intention behind the '?' card?
@Bilal-io I like your Abstention idea but I think we can make it easier by making it into a card:
  - "?" counts as nothing for averaging (so in the original example we get the Expected Result)
  - "Abstain" counts as nothing as well, but it's a signal to others that you aren't confused, just that you dont have a vote here.

This helps when running it because then when I see abstain I know that you are still voting, but you're not voting "?" which could cause me some confusion. (I take "?" to mean you still don't have enough information to vote which means we should talk more)

**Comment by 304NotModified** [comment]
I think the average should be `15?` for this case (no joke) . But not sure if the average could be a non number 🤔
